
dashboard:
  config_id: 'default'
  page_title: 'swag-tag'
  title: 'swag-tag: A Streamlit-based webapp for annotation of medical images and reports.'
  default_case_no: 0
  default_frac_img: 70
  window_default_range:
    - 0
    - 100
  window_default_min_max:
    {
      min_value: 0,
      max_value: 100,
    }
  max_img_buffer_size: 10
  report_columns:
    - 'examination'
    - 'indication'
    - 'history'
    - 'comparison'
    - 'technique'
    - 'findings'
    - 'impression'

llm-tag-server:
  endpoint: llm-tag-server
  port: 5000
  default_llm: "llama-2-70b-4bit"

sql:
  study_table:
    {
      table_name: 'studies',
      columns:
        {
          'PatientID': 'character varying(256)',
          'StudyInstanceUID': 'character varying(256)',
          'AccessionNumber': 'character varying(256)',
          'creation_time': 'timestamp',
        },
      prim_key: 'StudyInstanceUID',
      foreign_mapping:
        {
        },
    }
  reports_table:
    {
      table_name: 'reports',
      columns:
        {
          'PatientID': 'character varying(256)',
          'StudyInstanceUID': 'character varying(256)',
          'AccessionNumber': 'character varying(256)',
          'report_uri': 'character varying(256)',
          'creation_time': 'timestamp',
          'examination': 'text',
          'indication': 'text',
          'history': 'text',
          'comparison': 'text',
          'technique': 'text',
          'findings': 'text',
          'impression': 'text',
        },
      prim_key: 'AccessionNumber',
      foreign_mapping:
        {
          'studies': 'StudyInstanceUID',
        },
    }

  image_uris_table:
    {
      table_name: 'image_uris',
      columns:
        {
          'PatientID': 'character varying(256)',
          'StudyInstanceUID': 'character varying(256)',
          'SeriesInstanceUID': 'character varying(256)',
          'AccessionNumber': 'character varying(256)',
          'image_uri': 'character varying(256)',
          'creation_time': 'timestamp',
        },
      prim_key: 'SeriesInstanceUID',
      foreign_mapping:
        {
          'reports': 'AccessionNumber',
          'studies': 'StudyInstanceUID',
        },
    }
  #  reports_uris_table:
  #    {
  #      table_name: 'reports_uris',
  #      columns:
  #        {
  #          'PatientID': 'character varying(256)',
  #          'StudyInstanceUID': 'character varying(256)',
  #          'SeriesInstanceUID': 'character varying(256)',
  #          'AccessionNumber': 'character varying(256)',
  #          'report_uri': 'character varying(256)',
  #          'creation_time': 'timestamp',
  #        },
  #      prim_key: 'AccessionNumber',
  #      foreign_mapping:
  #        {
  #          'reports': 'AccessionNumber'
  #        },
  #    }
  result_table:
    {
      table_name: 'annotations_swag_tag',
      columns:
        {
          'annotation_id': 'SERIAL',
          'StudyInstanceUID': 'character varying(256)',
          'AccessionNumber': 'character varying(256)',
          'annotation_json': 'jsonb',
          'creation_time': 'timestamp',
          'author': 'character varying(256)',
        },
      prim_key: 'annotation_id',
      timestamp_col: 'creation_time',
      json_col: 'annotation_json',
      user_col: 'author',
      foreign_mapping:
        {
          'reports': 'AccessionNumber',
          'studies': 'StudyInstanceUID'
        },
    }
  config_table:
    {
      table_name: 'dash_conf',
      columns:
        {
          'config_id': 'character varying(256)',
          'config_json': 'jsonb',
          'creation_time': 'timestamp',
        },
      json_col: 'config_json',
      prim_key: 'config_id',
      timestamp_col: 'creation_time',
      foreign_mapping:
        {
        },

    }
  user_table:
    {
      table_name: 'users',
      columns:
        {
          'user_id': 'SERIAL',
          'user_name': 'character varying(256) UNIQUE',
          'creation_time': 'timestamp',
        },
      prim_key: 'user_id',
      user_col: 'user_name',
      timestamp_col: 'creation_time',
      foreign_mapping:
        {
        },

    }
