structures:
  Prior Examinations: [
    '<Free text>',
  ]
  Limited Assessability: [
    'no',
    'incomplete depiction',
    'reduced inspiratory depth',
    'Patient rotated insufficiently to the right',
    'Patient rotated insufficiently to the left',
    'Cranially angulated incorrectly',
    'Caudally angulated incorrectly',
  ]
  Foreign Material: [
    'none'
    'venous catheter',
    'pleural/ thoracic drainage',
    'tracheal cannula',
    'endotracheal tube (ETT)',
    'nasogastric tube',
    'mediastinal/pericardial drain',
    'valve replacement',
    'arterial catheter',
    '<Free text>',
  ]
  Diaphragm: [
    'regular position',
    'elevated due to shallow inspiration',
    'diaphragmatic elevation',
    'diaphragmatic depression',
    'diaphragmatic eventration'
  ]
  Abdominal Cavity: [
    'regular',
    'pneumoperitoneum / abdominal free air',
    'dilated bowel',
    '<Free text>'
  ]
  Pneumothorax: [
    'none',
    'Loculated pneumothorax',
    'Interlobular/fissural pneumothorax',
    'Tension pneumothorax',
  ]
  Pleural Effusion: [
    'none',
    'pleural effusion',
    'adhesive effusion components',
  ]
  Ventilation Disorders: [
    'none',
    'subsegmental atelectasis',
    'Plate atelectasis',
    'Compression atelectasis',
    'Round atelectasis',
    'Obstructive atelectasis',
  ]
  Inflammatory Infiltrates: [
    'none',
    'possible',
    'urgent suspicion/ highly likely',
  ]
  Pulmonary Edema: [
    'none',
    'interstitial pulmonary edema',
    'alveolar pulmonary edema',
    'Reexpansion edema',
  ]
  Heart: [
    'regular',
    'enlarged due to projection (a.p. projection, misrotation) and/or shallow inspiration',
    'Cardiomegaly',
    'Pneumopericardium',
  ]
  Mediastinum: [
    'displaced due to misrotation',
    'widened'
  ]
  Bony Structures: [
    'regular',
    '<Free text>',
  ]
  Soft Tissue Envelope: [
    'regular',
    'Emphysema',
    'asymmetric swelling',
    'asymmetric mammary shadow',
    'Severe obesity',
  ]

attributes:
  opt_side:
    - 'right'
    - 'left'
    - 'both sides'
  opt_widening:
    - 'to left'
    - 'to right'
    - 'symmetric'
  multi_height:
    - 'Upper field'
    - 'Middle field'
    - 'Lower field'
  mediastinal_loc:
    - 'midline '
    - 'displaced to the right (not rotationally related)'
    - 'displaced to the left (not rotationally related)'
  opt_pneumomediastinum:
    - 'no pneumomediastinum'
    - 'pneumomediastinum'
  opt_severity:
    - 'mild'
    - 'moderate'
    - 'extensive / marked'
  opt_foreign_body:
    - 'not mentioned'
    - 'regular placement'
    - 'misplaced'

default_attr_options: [ ]

attr_options:
  Pneumothorax:
    - side
    - multi_height
  Ventilation disorders:
    - side
    - multi_height
  Inflammatory Infiltrates:
    - side
    - multi_height
    - opt_severity
  Mediastinum:
    - mediastinal_loc
    - opt_widening
    - opt_pneumomediastinum
  Foreign Material:
    - opt_foreign_body