orthanc:
  host: localhost
  port: 8042
  protocol: http
  source_modality: PHOENIX
  max_workers: 16

db:
  host: localhost
  port: 5001
  user: postgres
  password: postgres
  dbname: swag

local_fs:
  host: localhost
  user: flaqua
  rootdir: /home/group_data/shared_data/mimic
  datadir: files
  tablesdir: tables
  fname: instance_tags.csv

dashboard:
  page_title: 'swag-tag'
  title: 'swag-tag: A Streamlit-based webapp for annotation of medical images and reports.'
  window_default_range:
    - 20
    - 80
  window_default_min_max:
    {
      min_value: 0,
      max_value: 100,
    }
  max_img_buffer_size: 10
  report_columns:
    - 'examination'
    - 'indication'
    - 'history'
    - 'comparison'
    - 'technique'
    - 'findings'
    - 'impression'


sql:
  study_table:
    {
      table_name: 'studies',
      columns:
        {
          'PatientID': 'character varying(256)',
          'StudyInstanceUID': 'character varying(256)',
          'AccessionNumber': 'character varying(256)',
          'creation_time': 'timestamp',
        },
      prim_key: 'StudyInstanceUID',
      foreign_mapping:
        {
        },
    }
  reports_table:
    {
      table_name: 'reports',
      columns:
        {
          'PatientID': 'character varying(256)',
          'StudyInstanceUID': 'character varying(256)',
          'AccessionNumber': 'character varying(256)',
          'report_uri': 'character varying(256)',
          'creation_time': 'timestamp',
          'examination': 'text',
          'indication': 'text',
          'history': 'text',
          'comparison': 'text',
          'technique': 'text',
          'findings': 'text',
          'impression': 'text',
        },
      prim_key: 'AccessionNumber',
      foreign_mapping:
        {
          'studies': 'StudyInstanceUID',
        },
    }

  image_uris_table:
    {
      table_name: 'image_uris',
      columns:
        {
          'PatientID': 'character varying(256)',
          'StudyInstanceUID': 'character varying(256)',
          'SeriesInstanceUID': 'character varying(256)',
          'AccessionNumber': 'character varying(256)',
          'image_uri': 'character varying(256)',
          'creation_time': 'timestamp',
        },
      prim_key: 'SeriesInstanceUID',
      foreign_mapping:
        {
          'reports': 'AccessionNumber',
          'studies': 'StudyInstanceUID',
        },
    }
  #  reports_uris_table:
  #    {
  #      table_name: 'reports_uris',
  #      columns:
  #        {
  #          'PatientID': 'character varying(256)',
  #          'StudyInstanceUID': 'character varying(256)',
  #          'SeriesInstanceUID': 'character varying(256)',
  #          'AccessionNumber': 'character varying(256)',
  #          'report_uri': 'character varying(256)',
  #          'creation_time': 'timestamp',
  #        },
  #      prim_key: 'AccessionNumber',
  #      foreign_mapping:
  #        {
  #          'reports': 'AccessionNumber'
  #        },
  #    }
  result_table:
    {
      table_name: 'annotations',
      columns:
        {
          'annotation_id': 'character varying(256)',
          'StudyInstanceUID': 'character varying(256)',
          'AccessionNumber': 'character varying(256)',
          'annotation': 'jsonb',
          'creation_time': 'timestamp',
        },
      prim_key: 'annotation_id',
      foreign_mapping:
        {
          'reports': 'AccessionNumber',
          'studies': 'StudyInstanceUID'
        },
    }
  config_table:
    {
      table_name: 'dash_conf',
      columns:
        {
          'config_id': 'character varying(256)',
          'config_json': 'jsonb',
          'creation_time': 'timestamp',
        },
      json_col: 'config_json',
      prim_key: 'config_id',
      foreign_mapping:
        {
        },

    }
