orthanc:
  host: localhost
  port: 8042
  protocol: http
  source_modality: PHOENIX
  max_workers: 16

db:
  host: localhost
  port: 5678
  user: postgres
  password: postgres
  dbname: swag

local_fs:
  host: localhost
  user: flaqua
  rootdir: /home/group_data/shared_data/swag
  datadir: data
  tablesdir: data/tables
  fname: instance_tags.csv

dashboard:
  page_title: 'swag-tag'
  title: 'swag-tag: A Streamlit-based webapp for annotation of medical images and reports.'
  window_default_range:
    - 20
    - 80
  window_default_min_max:
    {
      min_value: 0,
      max_value: 100,
    }

sql:
  image_uris_table:
    {
      table_name: 'image_uris',
      columns:
        {
          'PatientID': 'character varying(256)',
          'StudyInstanceUID': 'character varying(256)',
          'SeriesInstanceUID': 'character varying(256)',
          'AccessionNumber': 'character varying(256)',
          'image_fp': 'character varying(256)',
          'creation_time': 'timestamp',
        },
      prim_key: 'SeriesInstanceUID',
      foreign_mapping:
        {
          'reports': 'AccessionNumber',
        },
    }
  reports_table:
    {
      table_name: 'reports',
      columns:
        {
          'PatientID': 'character varying(256)',
          'StudyInstanceUID': 'character varying(256)',
          'SeriesInstanceUID': 'character varying(256)',
          'AccessionNumber': 'character varying(256)',
          'report_fp': 'character varying(256)',
          'creation_time': 'timestamp',
        },
      prim_key: 'AccessionNumber',
      foreign_mapping:
        {
          'image_uris': 'StudyInstanceUID'
        },
    }
  result_table:
    {
      table_name: 'annotations',
      columns:
        {
          'annotation_id': 'character varying(256)',
          'StudyInstanceUID': 'character varying(256)',
          'AccessionNumber': 'character varying(256)',
          'annotation': 'jsonb',
          'creation_time': 'timestamp',
        },
      prim_key: 'annotation_id',
      foreign_mapping:
        {
          'reports': 'AccessionNumber',
          'image_uris': 'StudyInstanceUID'
        },
    }
  config_table:
    {
      table_name: 'configuration',
      columns:
        {
          'config_id': 'character varying(256)',
          'annotation': 'jsonb',
          'creation_time': 'timestamp',
        },
      prim_key: 'config_id',
    }
